#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-

import os
import time
import syslog
import pymongo 
from pymongo import Connection
import soittilaFiles as f
import datetime

def getAika():
    now = datetime.datetime.now()
    aika = now.strftime("%H:%M:%S-%d.%m.%Y")
    return aika

def getTemp(anturi):
    f = open(anturi)
    s = f.readline()
    d = round(float(s.strip()), 0)
    i = int(d)
    return i    

def getTimeStamp():
    t = datetime.datetime.now()
    return t

def dateToStamp(date):
    stamppy = int(time.mktime(time.strptime(date, '%Y:%m:%d-%H.%M.%S')))
#    stamppy = int(time.mktime(time.strptime(date, '%H:%M:%S-%d.%m.%Y')))
    return stamppy
# dateToStamp('19:02:00-23.01.2012')


try:
    while(1):
        syslog.syslog('Lampötilojen Processing started')
        connection = Connection('localhost', 27017)
        db = connection.soittila_lampotilat
        uudet_lampotilat = [{"anturi": "puukattila","lampotila": getTemp(f.puukattila),"date": getAika(), "stamp": getTimeStamp()},
            {"anturi": "varaajaUp","lampotila": getTemp(f.varaajaUp),"date": getAika(),"stamp": getTimeStamp()},
            {"anturi": "varaajaDown","lampotila": getTemp(f.varaajaDown),"date": getAika(),"stamp": getTimeStamp()},
            {"anturi": "kattilaGold","lampotila": getTemp(f.kattilaGold),"date": getAika(),"stamp": getTimeStamp()},
            {"anturi": "kattilaHot","lampotila": getTemp(f.kattilaHot),"date": getAika(),"stamp": getTimeStamp()},
            {"anturi": "patteriL","lampotila": getTemp(f.patteriL),"date": getAika(),"stamp": getTimeStamp()},
            {"anturi": "LLlahto","lampotila": getTemp(f.LLlahto),"date": getAika(),"stamp": getTimeStamp()},
            {"anturi": "kattilaSw","tila": getTemp(f.kattilaSw),"date": getAika(),"stamp": getTimeStamp()},
            {"anturi": "laskuriA","lukema": getTemp(f.laskuriA),"date": getAika(),"stamp": getTimeStamp()},
            {"anturi": "laskuriB","lukema": getTemp(f.laskuriB),"date": getAika(),"stamp": getTimeStamp()},
            {"anturi": "maalampo","lampotila": getTemp(f.maalampo),"date": getAika(),"stamp": getTimeStamp()},
            {"anturi": "ulkoP","lampotila": getTemp(f.ulkoP),"date": getAika(),"stamp": getTimeStamp()},
            {"anturi": "ulkoE","lampotila": getTemp(f.ulkoE),"date": getAika(),"stamp": getTimeStamp()},
            {"anturi": "akWcLattia","lampotila": getTemp(f.akWcLattia),"date": getAika(),"stamp": getTimeStamp()},
            {"anturi": "khh","lampotila": getTemp(f.khh),"date": getAika(),"stamp": getTimeStamp()},
            {"anturi": "olohuone","lampotila": getTemp(f.olohuone),"date": getAika(),"stamp": getTimeStamp()}, 
            {"anturi": "makuuhuone","lampotila": getTemp(f.makuuhuone),"date": getAika(),"stamp": getTimeStamp()}, 
            {"anturi": "sauna","lampotila": getTemp(f.sauna),"date": getAika(),"stamp": getTimeStamp()}]
        lampotilat = db.soittila_lampotilat
        lampotilat.insert(uudet_lampotilat)
        syslog.syslog('Lämpötilat päivitetty')
        time.sleep(600)

except IOError:
    syslog.syslog(syslog.LOG_ERR, 'Ollaan IO Errorissa')
