#!/bin/sh
SERVICE='lampo2mongo'
SERVICEA='lamposerveri'
SERVICEB='owfs'

if ps ax | grep -v grep | grep $SERVICE > /dev/null
then
    logger -t checker "#********************************************"
    logger -t checker "$SERVICE service running, everything is fine"
else
    sendEmail -f Lampo2Mongo@sauna.dy.fi  -t tomi.lindstrom@aina.fi  -s smtp.kolumbus.fi  -u "Lampo2Mongo"  -m "Service is down, tried to reboot. Pleace check!" -q
    sudo /etc/init.d/lampo2mongo stop > /dev/null
    sudo /etc/init.d/lampo2mongo start > /dev/null
    logger -t checker "Email sent and $SERVICE service Restarted, should be fine now"
fi


if ps ax | grep -v grep | grep $SERVICEA > /dev/null
then
    logger -t checker "$SERVICEA service running, everything is fine"
else
    sendEmail -f Lamposerveri@sauna.dy.fi  -t tomi.lindstrom@aina.fi  -s smtp.kolumbus.fi  -u "Lamposerveri"  -m "Service is down, tried to reboot. Pleace check!" -q
    sudo /etc/init.d/lamposerveri stop > /dev/null
    sudo /etc/init.d/lamposerveri start > /dev/null
    logger -t checker "Email sent and $SERVICEA service Restarted, should be fine now"
fi

if ps ax | grep -v grep | grep $SERVICEB > /dev/null
then
    logger -t checker "$SERVICEB service running, everything is fine"
    logger -t checker "********************************************#"
else
    sendEmail -f owfs@sauna.dy.fi  -t tomi.lindstrom@aina.fi  -s smtp.kolumbus.fi  -u "OWFS"  -m "1-Wire Service is down, tried to reboot. Pleace check!" -q
    sudo /etc/init.d/owfs.sh stop > /dev/null
    sudo /etc/init.d/owfs.sh start > /dev/null
    logger -t checker "Email sent and $SERVICEB service Restarted, should be fine now"
fi
if  ! ls /mnt/1wire/uncached/10.70F938010800/temperature -f > /dev/null
then
    sendEmail -f owfs@sauna.dy.fi  -t tomi.lindstrom@aina.fi  -s smtp.kolumbus.fi  -u "OWFS"  -m "1-Wire Service is down, tried to reboot. Pleace check!" -q
    sudo /etc/init.d/owfs.sh stop > /dev/null
    sudo /etc/init.d/owfs.sh start > /dev/null
    logger -t checker "Email sent and $SERVICEB service Restarted, should be fine now"
fi
