#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
import os
import httplib
import time
import syslog
from time import strftime,localtime

puukattila = '/var/www/server/puuKattila.html'
varaajaUp = '/var/www/server/varaajaUp.html'
varaajaDown = '/var/www/server/varaajaDown.html'
kattilaGold = '/var/www/server/kattilaCold.html'
kattilaHot = '/var/www/server/kattilaHot.html'
patteriL = '/var/www/server/patteriL.html'
LLlahto = '/var/www/server/LLlahto.html'
kattilaSw = '/var/www/server/kattilaSw.html'
laskuriA = '/var/www/server/laskuriA.html'
laskuriB = '/var/www/server/laskuriB.html'
maalampo = '/var/www/server/maalampo.html'
ulkoE = '/var/www/server/ulkoE.html'
ulkoP = '/var/www/server/ulkoP.html'
akWcLattia = '/var/www/server/akWcLattia.html'
khh = '/var/www/server/khh.html'
olohuone = '/var/www/server/olohuone.html'
makuuhuone = '/var/www/server/makuuhuone.html'
sauna = '/var/www/server/sauna.html'

khhYraja = 23
khhAraja = 22
khhLattiaYraja = 32
khhLattiaAraja = 29

# Change float number from OWFS temperature file to integer
def toint(file):
    f = open(file)
    s = f.readline()
    d = round(float(s.strip()), 0)
    i = int(d)
    return i

def getLampo(file):
    f = open(file)
    s = f.readline()
    d = round(float(s.strip()), 0)
    l = str(d)
    return l

def releTila(relay):
    relaya = str(relay)
    connection = httplib.HTTPConnection('10.10.10.54')
    connection.request('GET', '/rele/'+ relaya)
    tila = connection.getresponse()
    tila = tila.read()
    connection.close()
    relaya = int(relaya)
    tila = int(tila)
    if relaya < 5 and tila < 2:
        tila = 0
    if tila == 1023:
        tila = 1    
    return str(tila)
    
def saadaOn(rele):
    relaya = str(rele)
    connection = httplib.HTTPConnection('10.10.10.54')
    connection.request('GET', '/on/'+ relaya)
    response = connection.getresponse()
    resp = response.read()
    connection.close()    

def saadaOff(rele):
    relaya = str(rele)
    connection = httplib.HTTPConnection('10.10.10.54')
    connection.request('GET', '/off/'+ relaya)
    response = connection.getresponse()
    resp = response.read()
    connection.close()

try:
    while(1):
        khhLampo = toint(khh)
        akWcLattiaLampo = toint(akWcLattia)
        akWcLattiaLampoStr = getLampo(akWcLattia)
        saunaLampoStr = getLampo(sauna)
        aikaNyt = time.strftime("%H%M", localtime())
        rele2 = releTila(2)
        rele1 = releTila(1)
        syslog.syslog('Lampötilojen Säätö Processing started')
        if (akWcLattiaLampo < khhLattiaAraja) and (rele2 == '0'):
            saadaOn(2)
            syslog.syslog('Säädettiin rele 2 on ** Lattia ' + akWcLattiaLampoStr)
        if (akWcLattiaLampo > khhLattiaYraja) and (rele2 == '1'):
            saadaOff(2)
            syslog.syslog('Säädettiin rele 2 off ** Lattia ' + akWcLattiaLampoStr)
        if ('2100' < aikaNyt > '1800') and (rele1 == '0'):
            saadaOn(1)
            syslog.syslog('Säädettiin rele 1 on ** Sauna lämpö ' + saunaLampoStr)
        if (aikaNyt < '1800') and (aikaNyt > '2100') and (rele1 == '1'):
            saadaOff(1)
            syslog.syslog('Säädettiin rele 1 off ** Sauna lämpö ' + saunaLampoStr)
	if (aikaNyt > '2100') and (aikaNyt < '0400) and rele3 == '0'):
	    saadaOn(3)
	else:
	    saadaOff(3)
        syslog.syslog('Lampötilojen Säätö Processing: Aloitetaan 600 ms Sleep')
        time.sleep(600)
    
except IOError:
        syslog.syslog(syslog.LOG_ERR, 'Lamposerveri, ei saada yhteyttä lämpötiloihin: ')
	pass
